appInfo:
  port: 8888
dbInfo:
  adress: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  showsql: true
  dbName: "ginweb"
redis:
  addr: "127.0.0.1"
  port: "6379"
  password: "123456"
  db: 0
log:
  level: "debug"
  encoding: "json"
  path: "./ginweb.log"